### ISSUE TITLE
Renaming of branches

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#17]
For consistency with other JuliaAI repositories:

- rename the default branch from `main` to `dev`

- when preparing for first release, duplicate `dev`, calling it `master` and register the `master` branch (in JuliaHub, enter `master` as the branch - don't use "default"). 

The protocol for development is to make all new PR's to the `dev` branch for review. When a new release is to be tagged, a final `master <- dev` PR titled "For a 0.?.? release" is made and merged, and the `master` branch used for the new release. Instead of using JuliaHub for this, I find it convenient to use `@JuliaRegistrator`, which is already set up for JuliaAI repos.

**Comment by EssamWisam** [comment]
Done. Initial release is already out.
