### ISSUE TITLE
Naming the structs

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#27]
I will re-iterate my complaint about "_t" in "SMOTE_t". 

The user only interested in TableTransforms can do `using Imbalance.TableTransforms`; the user only interested in MLJ models can do `using Imbalance.MLJ`. The submodules `MLJ` and `TableTransforms` can both `export SMOTE` with no problems because `Imbalance` does not specifically import either submodule with a `using` statement. I really think this is the cleanest and most Julian solution. 

https://github.com/JuliaAI/Imbalance.jl/blob/a5455af3d522e8112786f522e89a4b294fae5af2/src/smoten/interface_tables.jl#L3

**Comment by EssamWisam** [comment]
█▀▀ █▀█ █▄░█ █░█ █ █▄░█ █▀▀ █▀▀ █▀▄
█▄▄ █▄█ █░▀█  ▀▄▀  █ █░▀█ █▄▄ ██▄   █▄▀

**Comment by EssamWisam** [comment]
However, it may not be that easy to call the module the same name as the external package if both are imported according to my trials.

**Comment by ablaom** [comment]
I guess we sorted this on Slack, yes?

**Comment by EssamWisam** [comment]
> I guess we sorted this on Slack, yes?

Yes and it's solved. Will close.
