### ISSUE TITLE
General comment about types in functions signatures

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#30]
While structs should avoid abstract types, most developers avoid overly specific typing in the signatures of functions, to keep them as generic as possible. A winning feature of Julia is how many packages  just work together, as if by magic, through the use of generic code. See for example [here](https://github.com/ablaom/HelloJulia.jl/blob/dev/notebooks/pkg_composability/notebook.ipynb). A more serious example is automatic differentiation. In one approach, derivatives are tracked by creating a new concrete type `<: AbstractFloat` that stores the derivative in addition to the value of something. Any `AbstractFloat`-generic function can be auto-differentiated in this approach, but not if the function is typed `Float64`, say.  

It is true that you may want to make types stricter to prevent the user providing inputs that you know will lead to silently incorrect behaviour. That is the exception to the general rule above. But generally, this only applies at the level of the top-level user-exposed (public) functions. There is some discussion about the pitfalls of too much genericity [here](https://discourse.julialang.org/t/discussion-on-why-i-no-longer-recommend-julia-by-yuri-vishnevsky/81151) that every Julia developer should be aware of. 

Following this long preamble, I suggest there is no need to annotate the type of *any* of the arguments of this private function:

https://github.com/JuliaAI/Imbalance.jl/blob/1d5da71d28f693f620e08c16cd8b6a0255a3f52e/src/smotenc/smotenc.jl#L80

Perhaps, for readability, `X::AbstractMatrix` doesn't hurt, but you could just as well indicate this with a code comment. 

This comment obviously applies to a lot of the Imbalance.jl code.

**Comment by EssamWisam** [comment]
Discussed in the call
