### ISSUE TITLE
Use of absolute tolerances in testing

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#35]
https://github.com/JuliaAI/Imbalance.jl/blob/1d5da71d28f693f620e08c16cd8b6a0255a3f52e/test/test_utils.jl#L84

An absolute tolerance of 0.01 could be pretty lousy. I wonder if it is more correct to specify a relative tolerance, which is what `isapprox` does by default. Something like this:

```julia
function is_in_between(a::T b::T, c::T; rtol = sqrt(eps(T)) where T<:Real
    dist_ab = sqrt(sum((a .- b) .^ 2))
    dist_ac = sqrt(sum((a .- c) .^ 2))
    dist_total = sqrt(sum((b .- c) .^ 2))
    return isapprox(dist_ab + dist_ac, dist_total; rol)
end
```

**Comment by EssamWisam** [comment]
Discussed in the call.
