### ISSUE TITLE
Documentation is not live yet

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#42]
Clicking on the doc badge gives a 404. 

Once you have made the repo public, you may need a dummy PR do regenerate the docs. Did you set up your secrets/deploy keys?

**Comment by EssamWisam** [comment]
@ablaom It is now. [Check](https://juliaai.github.io/Imbalance.jl/dev/).

**Comment by ablaom** [comment]
Your link indeed works but the readme badge does not take me there. It just displays the badge gif.
