### ISSUE TITLE
Editorial suggestion

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#49]
https://github.com/JuliaAI/Imbalance.jl/blob/860e549ad3d3c140ceff04620252087b9c8311fe/docs/src/index.md?plain=1#L74

Avoid statements like "...and still under development" and "The package so far...". Just describe what the pkg does *now*.  One day you *won't* be developing this pkg any more; are you going to go back and edit these statements? Probably not.  Future plans can appear under your Contributor (or Road Map) section.  

Alternatively, list *all* features, actual and planned, but put check boxes next to them to indicate what is actually implemented. This makes for easy maintenance in an actively developing pkg.

**Comment by EssamWisam** [comment]
Of course my assumption while writing in that way is that I will update the README as I progress through the project. The final version would of course not include such terms. I removed them for now regardless and may also recommend algorithms to implement for contribution.
