### ISSUE TITLE
Editorial 

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#51]
When defining a term use italics or boldface, rather than code font. So

- *scientific types* ✅ 
- `scitype` ✅ 
- `scientific types` ❎ 

https://github.com/JuliaAI/Imbalance.jl/blob/4894d1f5146a6e9965bc901eb050187bab48ddc8/docs/src/walkthrough.md?plain=1#L46

**Comment by EssamWisam** [comment]
Thank you for the note.
