### ISSUE TITLE
Explaining scientific types

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#52]
It's nice that you include a section on type coercion, although I find this explanation misleading:

"The package will try to automatically infer the element scientific types for each column but allows us as developers to correct them by coercion if needed ."

It's not that `scitype` *guesses* or *infers* the scientific type of the data (although there is a function for that, `autotype`). Rather, `scitype` articulates a specific, concrete (and opinionated) convention about the scientific context or meaning of data, based on machine representation. Others may disagree about whether the convention is ideal, but to agree on *some* convention is useful, so users can focus on the real-world meaning of their data, rather than on the representation.  Algorithms, such as MLJ algorithms, that buy into the ScientificTypes.jl convention (as articulated by `scitype`) articulate their type requirements in terms of the convention and make an implicit promise to treat the data accordingly. Thus a linear model might require all features to have `Continuous` element scitype, (which includes, as it happens all `AbstractFloat` machine types) and treats the data as if it really is "continuous" in the real world. 

Viewed in this way, applying `coerce` to data is not correcting "bad inference" on the part of `scitype`. Rather it is ensuring that the machine representation of data conforms to what the algorithms expect, consistent with the actual "real world" interpretation of the data these algorithms were designed for. 

Of course, you're not going to say all that in your tutorial. I just wanted to flag how the inventor of scitypes had to scratch his head after reading your sentence 😉

**Comment by EssamWisam** [comment]
@ablaom, sorry for not changing this promptly.  Thank you, "infer" is indeed really misleading here. Consider if I replace it with the following

 """The package uses a default scientific type for elements of each column depending on the machine type but allows us to coerce them to other scientific types if needed."""

# continuation
For instance, these are the default scientific types for our data (and the corresponding machine types)
```julia
ScientificTypes.schema(df)
```

    ┌────────┬──────────┬─────────┐
    │ names  │ scitypes │ types   │
    ├────────┼──────────┼─────────┤
    │ Gender │ Textual  │ String7 │
    │ Height │ Count    │ Int64   │
    │ Weight │ Count    │ Int64   │
    │ Index  │ Count    │ Int64   │
    └────────┴──────────┴─────────┘

**Comment by ablaom** [comment]
I think "default" is still not right the right connotation. 

How about the offending sentence is replaced with:

"We use `schema(X)` to see how each features is currently going to be interpreted by the resampling algorithms: "

Then replace the entire paragraph following the schema output with:

"To change encodings that are leading to incorrect interpretations (true for all variable in this example), we use the `coerce` method, as follows:"
