### ISSUE TITLE
Review impact of MLJBase 1.0

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#58]
MLJBase 1.0 has just been released. As MLJBase is used in testing, and the most current release will usually be adopted, there may be some breakages to tests of the current package, if MLJBase measures are used in testing. 

See the [migration guide](https://github.com/alan-turing-institute/MLJ.jl/blob/measure/docs/src/performance_measures.md#packages-implementing-the-mlj-model-interface) for details. 

It is highly unlikely /src code will need to be changed.

**Comment by EssamWisam** [comment]
I don't think I use MLJBase measures in testing. Neither tests nor the guides break here.

**Comment by ablaom** [comment]
Could you also check your notebooks? If you are using MLJBase without MLJ, you will need to add StatisticalMeasures.jl to the Project.tom., if you want to update the Manifest to use the latest MLJBase. 

If you are using MLJ, then no change is needed now, or likely needed after a pending update to synch with MLJBase 1.0.

**Comment by EssamWisam** [comment]
In the notebooks where I use `MLJBase`, only `machine` and `transform` are used. Generally, notebooks that are explicit in the docs just use `MLJ`.
