### ISSUE TITLE
Issue to trigger Imbalance.jl releases

### ISSUE THREAD

**Issue by EssamWisam** [JuliaAI/Imbalance.jl#62]
@JuliaRegistrator register branch=master

Release notes:

Added the following resampling algorithms
- Random Walk Oversampling (RWO)
- Borderline SMOTE1
- Random Undersampling
- Cluster Undersampling
- EditedNearestNeighbors Undersampling
- Tomek Links Undersampling

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Added support for Julia 1.6
- Various documentation improvements

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

Fixed a bug causing issues for Julia 1.10

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Bug fix: corrected input and output scitypes for implemented static models

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

Bug fix: corrected input and output scitypes for SMOTEN and other scitypes in the documentation.

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

Bug fix: READEME and documentation improvements
New Feature: Random oversampling and undersampling can now handle missing values

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Bug fix: READEME and documentation improvements
- New Feature: Random oversampling and undersampling can now handle missing values

**Comment by EssamWisam** [comment]
@JuliaRegistrator register branch=master

Release notes:

Bug fix: READEME and documentation improvements
New Feature: Random oversampling and undersampling can now handle missing values

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Extend compatibility requirements for CategoricalArrays so that v1.0 is supported.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- (**breaking**) In the case of float values, bring the interpretation of `ratios` and `min_ratios` into line with python's [imbalance-learn](https://imbalanced-learn.org/stable/) (#113)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
