### ISSUE TITLE
Use of `columnnames`

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#7]
https://github.com/EssamWisam/Imbalance.jl/blob/a1df842ad005fa9ce37a3d95efd7e6fd279646c3/src/common.jl#L70

Unfortunately, the `columnnames` method in Tables.jl cannot be reliably applied to any table. Most of the time it does work, and I think we have abused the method in parts of MLJModels.jl. However, strictly speaking, the spec only requires that it be implemented as part of the `AbstractColumns` API (what you get when you call `Tables.columns(X)` on a table) or the `AbstractRow` API (what elements, ie rows,  in the iteration of `Tables.rows(X)` implements). 

```
help?> Tables.columnnames
  Tables.columnnames(::Union{AbstractColumns, AbstractRow}) => Indexable collection

  Retrieves the list of column names as an indexable collection (like a Tuple
  or Vector) for a AbstractColumns or AbstractRow interface object. The default
  definition calls propertynames(x). The returned column names must be unique.
```

@OkonSamuel What is your recommendation for extracting the header for an arbitrary table? In this particular case, the other operation we will always be doing is materialising the table as a matrix where observations are ~~columns~~ rows. (I looked over at ScientificTypes.jl [where this came up with `schema`](https://github.com/JuliaAI/ScientificTypes.jl/blob/10b332327e4723352d85699b4a119609d1062cd8/src/schema.jl#L121) but that code is so complicated...)

**Comment by OkonSamuel** [comment]
> Thank you so much @OkonSamuel for this insightful solution and explanation. My conclusion is if I am to follow the last approach you mentioned while being more careful about calling `Tables.columns` and assuming that the input is surely a table then I may do
> 
> ```julia
>     if Tables.columnaccess(x)
>        columns = Tables.columns(x)
>        names = Tables.columnnames(columns)
>        matrix = Tables.matrix(columns)
>     else
>         iter = iterate(Tables.rows(x))
>         names = iter === nothing ? () : Tables.columnnames(first(iter))
>         matrix = Tables.matrix(x)
>     end
> ```
> 
> Let me know if I am missing anything and thank you again.

@EssamWisam  Sorry, I forgot about this issue. Your code above is good. Just one change you need to make in terms of `Tables.matrix`

```julia
    if Tables.columnaccess(x)
        columns = Tables.columns(x)
        names = Tables.columnnames(columns)
        matrix = Tables.matrix(x)
     else
         iter = iterate(Tables.rows(x))
         names = iter === nothing ? () : Tables.columnnames(first(iter))
         matrix = Tables.matrix(x)
     end
> ```
