### ISSUE TITLE
SMOTEN `input_scitype` and doc string 

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#80]
```julia
julia> input_scitype(Imbalance.MLJ.SMOTEN)
Tuple{Union{Table{<:AbstractVector{<:Finite}}, AbstractMatrix{Finite}}, AbstractVector}
```
The `AbstractMatrix{Finite}` should be `Abstract{<:Finite}`. 

And the doc-string is contrary to this:

```
 Transform Inputs
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

    •  X: A matrix or table of floats where each row is an observation from the dataset

    •  y: An abstract vector of labels (e.g., strings) that correspond to the
       observations in X
```

**Comment by EssamWisam** [comment]
I understand why `<:Finite` (was a little sleepy last time I touched this, sorry) but why `Abstract` instead of `AbstractMatrix`? As for the docstring, yes, it should have agreed with the spec in `Imbalance.jl` docs, let me fix this.

**Comment by ablaom** [comment]
my bad. i meant `AbstractMatrix{<:Finite}}` 😳
