### ISSUE TITLE
JOSS paper minor issues

### ISSUE THREAD

**Issue by sylvaticus** [JuliaAI/Imbalance.jl#85]
Hello, great paper, just a few minor points for me:

a. Missing reference on line 31

b. "all four major types of resampling approaches" .. ok but which are these? From Table1 I could guess "Ensemble, Oversampling, Undersampling", but still missing one...

c. I think the sentence on BalanceModel/ MLJBalancing.jl comes too early.. I couldn't understood it from the paper, but from the readme in the package is ok.. I think you should skip it at that time, and eventually dedicate a few more lines after the design principles, well indicating that it isn't the MLJ interface for the package, that one is already in the Imbalance.jl package... 

[part of https://github.com/openjournals/joss-reviews/issues/6310 ]

**Comment by EssamWisam** [comment]
Thank you for the comments!

For (a), will try to fix the missing reference, I just remember following the syntax and not having it work.

For (b), they are described in the Summary section of the paper:
`Two prevalent strategies for mitigating class imbalance.... It may be also possible to achieve even greater performance by combining both approaches or by resampling the data multiple times and ....
`
In other words, the fourth type is combination methods which are possible thanks to `MLJBalancing`.

I still completely agree that it should be further clarified. I will consider enumerating them in the same bullet point.

For (c), @ablaom  what do you think? I think our options are to phrase the following in a better way or push it down after the design principles?
`
Additionally, we present a companion package, MLJBalancing.jl, which: (i)  facilitates the integration of resampling methods with classification models via the BalancedModel construct, to create a seamless machine learning pipeline that behaves like a single unified model;  and (ii) implements a general version of the EasyEnsemble algorithm presented in `

CC: @ablaom

**Comment by EssamWisam** [comment]
@sylvaticus I tried to improve all of (1), (2), (3) can you read the relevant sections of the paper and let me know if it's satisfactory now?

Thank you.
