### ISSUE TITLE
Add links to JOSS paper 

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/Imbalance.jl#99]
Could be a badge. Also worth explicitly providing the full BibTex entry somewhere?

```latex
@article{Wisam2024, 
    doi = {10.21105/joss.06310}, 
    url = {https://doi.org/10.21105/joss.06310}, 
    year = {2024}, 
    publisher = {The Open Journal}, 
    volume = {9}, 
    number = {95}, 
    pages = {6310}, 
    author = {Essam Wisam and Anthony Blaom}, 
    title = {Imbalance: A comprehensive multi-interface Julia toolbox to address class imbalance}, 
    journal = {Journal of Open Source Software} ,
}
````

**Comment by EssamWisam** [comment]
How about I add the badge but still keep the Bibtex entry as is? Have seen many repos putting the Bibtex at the bottom like this.

**Comment by ablaom** [comment]
> How about I add the badge but still keep the Bibtex entry as is?

As usual, a step ahead of me. I didn't realize it was already there. Perfect, thanks.

**Comment by EssamWisam** [comment]
Hahaha thanks!

> How about I add the badge...

Quite funnily, I have just found out I am a step ahead of myself xD, in particular I added the badge along with the Bibtex three weeks ago.
